PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> python --version
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ python --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> py --version    
Python 3.13.1
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> python -m pip --version
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try     
again.
At line:1 char:1
+ python -m pip --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> py -m pip --version     
>> 
pip 24.3.1 from C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip (python 3.13)
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install yt-dlp google-auth google-auth-oauthlib google-auth-httplib2 googleapiclient
>>
Requirement already satisfied: yt-dlp in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2025.1.26)
Collecting google-auth
  Downloading google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
ERROR: Could not find a version that satisfies the requirement googleapiclient (from versions: none)
ERROR: No matching distribution found for googleapiclient

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> ^C
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> --upgrade pip
At line:1 char:3
+ --upgrade pip
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --upgrade pip
+   ~~~~~~~
Unexpected token 'upgrade' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> -m pip install --upgrade pip
-m : The term '-m' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.       
At line:1 char:1
+ -m pip install --upgrade pip
+ ~~
    + CategoryInfo          : ObjectNotFound: (-m:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> python -m pip install --upgrade pip
>>
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try     
again.
At line:1 char:1
+ python -m pip install --upgrade pip
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> python -m pip install --upgrade pip
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try     
again.
At line:1 char:1
+ python -m pip install --upgrade pip
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install yt-dlp
>>
Requirement already satisfied: yt-dlp in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2025.1.26)

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>  py -m pip install --upgrade pip    
Requirement already satisfied: pip in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (24.3.1)
Collecting pip
  Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-25.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.6 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
  WARNING: The scripts pip.exe, pip3.13.exe and pip3.exe are installed in 'C:\Users\Asus\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-25.0
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install yt-dlp google-auth google-auth-oauthlib google-auth-httplib2 googleapiclient
>>
Requirement already satisfied: yt-dlp in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2025.1.26)
Collecting google-auth
  Using cached google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting google-auth-oauthlib
  Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting google-auth-httplib2
  Using cached google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
ERROR: Could not find a version that satisfies the requirement googleapiclient (from versions: none)
ERROR: No matching distribution found for googleapiclient

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> py --version
Python 3.13.1
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> ^C
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install google-api-python-client
>> 
Collecting google-api-python-client
  Downloading google_api_python_client-2.160.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 (from google-api-python-client)
  Using cached google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Using cached google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.24.1-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading protobuf-5.29.3-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.26.0-py3-none-any.whl.metadata (2.2 kB)
Collecting requests<3.0.0.dev0,>=2.18.0 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client)
  Downloading cachetools-5.5.1-py3-none-any.whl.metadata (5.4 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client)
  Downloading pyasn1_modules-0.4.1-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client)
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (from httplib2<1.dev0,>=0.19.0->google-api-python-client)
  Downloading pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client)
  Downloading certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Downloading google_api_python_client-2.160.0-py2.py3-none-any.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 11.3 MB/s eta 0:00:00
Downloading google_api_core-2.24.1-py3-none-any.whl (160 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 10.0 MB/s eta 0:00:00
Downloading google_auth-2.38.0-py2.py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.8/210.8 kB 6.5 MB/s eta 0:00:00
Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 5.4 MB/s eta 0:00:00
Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Downloading cachetools-5.5.1-py3-none-any.whl (9.5 kB)
Downloading googleapis_common_protos-1.66.0-py2.py3-none-any.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.7/221.7 kB 6.6 MB/s eta 0:00:00
Downloading proto_plus-1.26.0-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB ? eta 0:00:00
Downloading protobuf-5.29.3-cp310-abi3-win_amd64.whl (434 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.5/434.5 kB 9.0 MB/s eta 0:00:00
Downloading pyasn1_modules-0.4.1-py3-none-any.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.5/181.5 kB 5.4 MB/s eta 0:00:00
Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 6.5 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB ? eta 0:00:00
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Downloading certifi-2025.1.31-py3-none-any.whl (166 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 kB 10.4 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.4/102.4 kB 6.1 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 4.0 MB/s eta 0:00:00
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 kB 4.6 MB/s eta 0:00:00
Downloading urllib3-2.3.0-py3-none-any.whl (128 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.4/128.4 kB 7.4 MB/s eta 0:00:00
Installing collected packages: urllib3, uritemplate, pyparsing, pyasn1, protobuf, idna, charset-normalizer, certifi, cachetools, rsa, requests, pyasn1-modules, proto-plus, httplib2, googleapis-common-protos, google-auth, google-auth-httplib2, google-api-core, google-api-python-client
  WARNING: The script normalizer.exe is installed in 'C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt.exe, pyrsa-encrypt.exe, pyrsa-keygen.exe, pyrsa-priv2pub.exe, pyrsa-sign.exe and pyrsa-verify.exe are installed in 'C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-5.5.1 certifi-2025.1.31 charset-normalizer-3.4.1 google-api-core-2.24.1 google-api-python-client-2.160.0 google-auth-2.38.0 google-auth-httplib2-0.2.0 googleapis-common-protos-1.66.0 httplib2-0.22.0 idna-3.10 proto-plus-1.26.0 protobuf-5.29.3 pyasn1-0.6.1 pyasn1-modules-0.4.1 pyparsing-3.2.1 requests-2.32.3 rsa-4.9 uritemplate-4.1.1 urllib3-2.3.0

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install yt-dlp google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
>>
Requirement already satisfied: yt-dlp in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2025.1.26)
Requirement already satisfied: google-auth in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.38.0)
Collecting google-auth-oauthlib
  Using cached google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: google-auth-httplib2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.2.0)
Requirement already satisfied: google-api-python-client in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.160.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (5.5.1)   
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (0.4.1)    
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (4.9)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: httplib2>=0.19.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth-httplib2) (0.22.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client) (2.24.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client) (4.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.66.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (5.29.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.26.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httplib2>=0.19.0->google-auth-httplib2) (3.2.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.1)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4.1) 
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.3.0)       
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2025.1.31)   
Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 2.3 MB/s eta 0:00:00
Installing collected packages: oauthlib, requests-oauthlib, google-auth-oauthlib
  WARNING: The script google-oauthlib-tool.exe is installed in 'C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.      
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed google-auth-oauthlib-1.2.1 oauthlib-3.2.2 requests-oauthlib-2.0.0

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>  C:\Users\Asus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\lib\site-packages (24.0)
Collecting pip
  Using cached pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-25.0-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-25.0
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> pip install yt-dlp google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
>>
Requirement already satisfied: yt-dlp in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2025.1.26)
Requirement already satisfied: google-auth in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.38.0)
Requirement already satisfied: google-auth-oauthlib in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.2.1)
Requirement already satisfied: google-auth-httplib2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.2.0)
Requirement already satisfied: google-api-python-client in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.160.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (5.5.1)   
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (0.4.1)    
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth-oauthlib) (2.0.0)
Requirement already satisfied: httplib2>=0.19.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-auth-httplib2) (0.22.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client) (2.24.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-python-client) (4.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.66.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (5.29.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.26.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from httplib2>=0.19.0->google-auth-httplib2) (3.2.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4.1) 
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.3.0)       
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2025.1.31)   
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>    

clear

next::::::


PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>  & 'c:\Users\Asus\AppData\Local\Programs\Python\Python313\python.exe' 'c:\Users\Asus\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '65500' '--' 'c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py' 
Enter a math term (e.g., 100, square root, fraction): 100
Searching for sign language video for: 100
Traceback (most recent call last):
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 85, in <module>
    main()
    ~~~~^^
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 59, in main
    video_url = search_youtube(math_term)
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 21, in search_youtube
    ).execute()
      ~~~~~~~^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/search?q=100+in+sign+language&part=id&maxResults=1&type=video&key=YOUR_YOUTUBE_API_KEY&alt=json returned "API key not valid. Please pass a valid API key.". Details: "[{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}]">
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>  c:; cd 'c:\Users\Asus\OneDrive\Desktop\ProjectPY'; & 'c:\Users\Asus\AppData\Local\Programs\Python\Python313\python.exe' 'c:\Users\Asus\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '50447' '--' 'c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py'
Enter a math term (e.g., 100, square root, fraction): 100
Searching for sign language video for: 100
Downloading video from: https://www.youtube.com/watch?v=stCwx6SXgSA
[youtube] Extracting URL: https://www.youtube.com/watch?v=stCwx6SXgSA 
[youtube] stCwx6SXgSA: Downloading webpage 
[youtube] stCwx6SXgSA: Downloading tv client config 
[youtube] stCwx6SXgSA: Downloading player 9c6dfc4a 
[youtube] stCwx6SXgSA: Downloading tv player API JSON 
[youtube] stCwx6SXgSA: Downloading ios player API JSON 
[youtube] stCwx6SXgSA: Downloading m3u8 information 
[info] stCwx6SXgSA: Downloading 1 format(s): 616+251 
ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
Traceback (most recent call last):
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 85, in <module>
    main()
    ~~~~^^
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 67, in main
    download_video(video_url, output_directory)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python.py", line 38, in download_video
    ydl.download([video_url])
    ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3618, in download
    self.__download_wrapper(self.extract_info)(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3591, in wrapper
    res = func(*args, **kwargs)
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1637, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1793, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1852, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3024, in process_video_result
    self.process_info(new_info)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 177, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3450, in process_info
    self.report_error(f'{msg}. Aborting due to --abort-on-error')
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1095, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1034, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error              ffmpeg -version
>> C:\Users\Asus\OneDrive\Desktop\ProjectPY>
ffmpeg : The term 'ffmpeg' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.



::::::::::

PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> ^C
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> 
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY>  c:; cd 'c:\Users\Asus\OneDrive\Desktop\ProjectPY'; & 'c:\Users\Asus\AppData\Local\Programs\Python\Python313\python.exe' 'c:\Users\Asus\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '50728' '--' 'c:\Users\Asus\OneDrive\Desktop\ProjectPY\python1.py' 
Enter a math term (e.g., 100, square root, fraction): 100
Searching for sign language video for: 100
Downloading video from: https://www.youtube.com/watch?v=stCwx6SXgSA
[youtube] Extracting URL: https://www.youtube.com/watch?v=stCwx6SXgSA 
[youtube] stCwx6SXgSA: Downloading webpage 
[youtube] stCwx6SXgSA: Downloading tv client config 
[youtube] stCwx6SXgSA: Downloading player 9c6dfc4a 
[youtube] stCwx6SXgSA: Downloading tv player API JSON 
[youtube] stCwx6SXgSA: Downloading ios player API JSON 
[youtube] stCwx6SXgSA: Downloading m3u8 information 
[info] stCwx6SXgSA: Downloading 1 format(s): 616 
[hlsnative] Downloading m3u8 manifest 
[hlsnative] Total fragments: 55 
[download] Destination: MathSignVideos\100 Essential ASL Signs in 5 Minutes.mp4 
[download] 100% of   97.43MiB in 00:01:34 at 1.04MiB/s 
WARNING: stCwx6SXgSA: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically 
Uploading 100 Essential ASL Signs in 5 Minutes.mp4 to Google Drive...
Traceback (most recent call last):
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python1.py", line 86, in <module>
    main()
    ~~~~^^
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python1.py", line 78, in main
    file_id = upload_to_drive(video_path)
  File "c:\Users\Asus\OneDrive\Desktop\ProjectPY\python1.py", line 43, in upload_to_drive
    creds = service_account.Credentials.from_service_account_file(GOOGLE_DRIVE_CREDENTIALS, scopes=["https://www.googleapis.com/auth/drive"])
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\oauth2\service_account.py", line 260, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        filename, require=["client_email", "token_uri"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\auth\_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/your/service_account.json'
PS C:\Users\Asus\OneDrive\Desktop\ProjectPY> 


______________________

